version: 2
updates:
  - package-ecosystem: "conda"
    directory: "/" 
    schedule:
      interval: "weekly"
    workflow_dispatch:  # Manual trigger only
    open-pull-requests-limit: 0

  - package-ecosystem: "pip"
    directory: "/" 
    schedule:
      interval: "weekly"
    workflow_dispatch:  # Manual trigger only
    open-pull-requests-limit: 0 
