"""E2E tests for IonGROMACSExporter (Tab 5 — Ion).

Tests the ion exporter — the most complex exporter in the pipeline:
- Base files: .gro, .top, tip4p-ice.itp, ion.itp (GENERATED, not copied)
- ion.itp: contains NA and CL moleculetype sections with Madrid2019 parameters
- Guest ITP: copied when ion_structure has guests (guest_nmolecules > 0)
- No guest ITP: when ion_structure has no guests
- Solute ITP: copied when solutes present (solute_n_molecules > 0 + positions)
- Custom molecule ITP: copied when custom_molecule_count > 0 + positions + itp_path

The ion exporter is the final stage of the pipeline and carries forward ALL
conditional paths from previous exporters (guest, solute, custom molecule ITP).

Key difference from other exporters: ion.itp is GENERATED by write_ion_itp()
from gromacs_ion_export.py, NOT copied from a data directory like other ITPs.

Fixtures from conftest.py:
    - ion_structure: minimal IonStructure (2 water + 1 NA + 1 CL, no guests/solutes/custom)
    - mock_save_dialog: factory -> (save_path, dialog_patch, mb_patch)
"""

from pathlib import Path

import numpy as np
import pytest

from quickice.gui.export import IonGROMACSExporter
from quickice.structure_generation.types import IonStructure, MoleculeIndex
from quickice.structure_generation.moleculetype_registry import MoleculetypeRegistry


class TestIonGROMACSExporter:
    """End-to-end tests for ion GROMACS export (Tab 5)."""

    def test_export_creates_base_files(self, ion_structure, mock_save_dialog):
        """Export creates .gro, .top, tip4p-ice.itp, and ion.itp.

        The ion_structure fixture is minimal: 2 water + 1 NA + 1 CL,
        with no guests, solutes, or custom molecules. Only the four
        base files should be produced.
        """
        save_path, dialog_p, mb_p = mock_save_dialog("ions_1na_1cl.gro")
        exporter = IonGROMACSExporter(parent_widget=None)

        with dialog_p, mb_p:
            result = exporter.export_ion_gromacs(ion_structure)

        assert result is True
        tmp_path = Path(save_path).parent
        # Base files
        assert (tmp_path / "ions_1na_1cl.gro").exists()
        assert (tmp_path / "ions_1na_1cl.top").exists()
        assert (tmp_path / "tip4p-ice.itp").exists()
        # ion.itp — GENERATED, not copied from data directory
        assert (tmp_path / "ion.itp").exists()

    def test_ion_itp_is_generated_not_copied(self, ion_structure, mock_save_dialog):
        """ion.itp is GENERATED by write_ion_itp(), not copied from data directory.

        The generated ion.itp contains [ moleculetype ] sections for NA and CL
        with Madrid2019 parameters. This is distinct from other ITP files
        (tip4p-ice.itp, guest .itp) which are copied from the data directory.
        """
        save_path, dialog_p, mb_p = mock_save_dialog("ions_1na_1cl.gro")
        exporter = IonGROMACSExporter(parent_widget=None)

        with dialog_p, mb_p:
            result = exporter.export_ion_gromacs(ion_structure)

        assert result is True
        tmp_path = Path(save_path).parent
        ion_itp_content = (tmp_path / "ion.itp").read_text()

        # Contains moleculetype directive
        assert "[ moleculetype ]" in ion_itp_content

        # Contains NA moleculetype section
        assert "NA" in ion_itp_content

        # Contains CL moleculetype section
        assert "CL" in ion_itp_content

        # Contains Madrid2019 comment header (generated by write_ion_itp)
        assert "Madrid2019" in ion_itp_content

    def test_ion_itp_has_correct_charges(self, ion_structure, mock_save_dialog):
        """ion.itp has Madrid2019 charges: NA=+0.85, CL=-0.85.

        The Madrid2019 ion model uses scaled charges (±0.85 instead of ±1.0)
        to account for electronic polarization effects in TIP4P water models.
        """
        save_path, dialog_p, mb_p = mock_save_dialog("ions_1na_1cl.gro")
        exporter = IonGROMACSExporter(parent_widget=None)

        with dialog_p, mb_p:
            result = exporter.export_ion_gromacs(ion_structure)

        assert result is True
        tmp_path = Path(save_path).parent
        ion_itp_content = (tmp_path / "ion.itp").read_text()

        # NA charge is 0.85 (Madrid2019)
        # The ITP line format: "1    NA      1    NA    NA     1      0.85   22.9898"
        assert "0.85" in ion_itp_content, "NA charge 0.85 not found in ion.itp"

        # CL charge is -0.85 (Madrid2019)
        assert "-0.85" in ion_itp_content, "CL charge -0.85 not found in ion.itp"

    def test_no_guest_itp_when_no_guests(self, ion_structure, mock_save_dialog):
        """No guest ITP files when ion_structure has no guests.

        The ion_structure fixture has guest_nmolecules=0 and guest_atom_count=0.
        No ch4_hydrate.itp or thf_hydrate.itp should be in the output directory.
        """
        save_path, dialog_p, mb_p = mock_save_dialog("ions_1na_1cl.gro")
        exporter = IonGROMACSExporter(parent_widget=None)

        with dialog_p, mb_p:
            result = exporter.export_ion_gromacs(ion_structure)

        assert result is True
        tmp_path = Path(save_path).parent
        # No guest ITP files should exist
        assert not (tmp_path / "ch4_hydrate.itp").exists()
        assert not (tmp_path / "thf_hydrate.itp").exists()

    def test_guest_itp_copied_when_guests_present(self, mock_save_dialog):
        """Guest ITP is copied when ion_structure has guests.

        The exporter checks ion_structure.guest_nmolecules > 0 AND
        ion_structure.guest_atom_count > 0, then iterates molecule_index
        for mol_type == "guest" entries and detects the guest type via
        detect_guest_type_from_atoms(). For CH4 guests (5 atoms), the
        ch4_hydrate.itp should be copied to the output directory.
        """
        # Create IonStructure with CH4 guests
        ion = IonStructure(
            positions=np.zeros((15, 3)),  # 8 water + 2 ions + 5 CH4
            atom_names=[
                "OW", "HW1", "HW2", "MW",  # water mol 1
                "OW", "HW1", "HW2", "MW",  # water mol 2
                "NA",                       # sodium
                "CL",                       # chloride
                "C", "H", "H", "H", "H",   # CH4 guest
            ],
            cell=np.eye(3) * 3.0,
            molecule_index=[
                MoleculeIndex(0, 4, "water"),
                MoleculeIndex(4, 4, "water"),
                MoleculeIndex(8, 1, "na"),
                MoleculeIndex(9, 1, "cl"),
                MoleculeIndex(10, 5, "guest"),
            ],
            na_count=1,
            cl_count=1,
            report="test",
            guest_nmolecules=1,
            guest_atom_count=5,
        )

        save_path, dialog_p, mb_p = mock_save_dialog("ions_with_guest.gro")
        exporter = IonGROMACSExporter(parent_widget=None)

        with dialog_p, mb_p:
            result = exporter.export_ion_gromacs(ion)

        assert result is True
        tmp_path = Path(save_path).parent
        # Guest ITP should exist
        assert (tmp_path / "ch4_hydrate.itp").exists()

    def test_guest_itp_copied_when_guest_nmolecules_zero_but_molecule_index_has_guests(self, mock_save_dialog):
        """REGRESSION: Guest ITP is copied even when guest_nmolecules=0.

        Bug: When the workflow chain passes through CustomMoleculeStructure
        (which historically lacked guest_nmolecules), the resulting IonStructure
        may have guest_nmolecules=0 even though molecule_index has guest entries
        and guest_atom_count > 0. The exporter should use molecule_index-based
        detection (consistent with write_ion_top_file) so the guest ITP is copied
        even when guest_nmolecules is 0.
        """
        # Create IonStructure with CH4 guests but guest_nmolecules=0
        # (This is the bug condition from the hydrate→custom→solute→ion chain)
        ion = IonStructure(
            positions=np.zeros((15, 3)),  # 8 water + 2 ions + 5 CH4
            atom_names=[
                "OW", "HW1", "HW2", "MW",  # water mol 1
                "OW", "HW1", "HW2", "MW",  # water mol 2
                "NA",                       # sodium
                "CL",                       # chloride
                "C", "H", "H", "H", "H",   # CH4 guest
            ],
            cell=np.eye(3) * 3.0,
            molecule_index=[
                MoleculeIndex(0, 4, "water"),
                MoleculeIndex(4, 4, "water"),
                MoleculeIndex(8, 1, "na"),
                MoleculeIndex(9, 1, "cl"),
                MoleculeIndex(10, 5, "guest"),
            ],
            na_count=1,
            cl_count=1,
            report="test",
            guest_nmolecules=0,    # BUG CONDITION: 0 but molecule_index has guest!
            guest_atom_count=5,    # > 0, so .top file includes ch4_hydrate.itp
        )

        save_path, dialog_p, mb_p = mock_save_dialog("ions_with_guest.gro")
        exporter = IonGROMACSExporter(parent_widget=None)

        with dialog_p, mb_p:
            result = exporter.export_ion_gromacs(ion)

        assert result is True
        tmp_path = Path(save_path).parent
        # Guest ITP should exist even when guest_nmolecules=0
        assert (tmp_path / "ch4_hydrate.itp").exists(), (
            "ch4_hydrate.itp should be copied when molecule_index has guest entries, "
            "even if guest_nmolecules=0 (regression from CustomMoleculeStructure chain)"
        )

    def test_solute_itp_copied_when_solutes_present(self, mock_save_dialog):
        """Solute liquid ITP is copied when ion_structure has solutes.

        The exporter checks solute_n_molecules > 0 AND solute_positions
        is not None. It locates the solute liquid ITP from the data
        directory and copies it with atomtypes commented out.
        """
        # Create IonStructure with CH4 solutes
        ion = IonStructure(
            positions=np.zeros((15, 3)),  # 8 water + 2 ions + 5 solute atoms
            atom_names=[
                "OW", "HW1", "HW2", "MW",  # water mol 1
                "OW", "HW1", "HW2", "MW",  # water mol 2
                "NA",                       # sodium
                "CL",                       # chloride
                "C", "H", "H", "H", "H",   # CH4 solute
            ],
            cell=np.eye(3) * 3.0,
            molecule_index=[
                MoleculeIndex(0, 4, "water"),
                MoleculeIndex(4, 4, "water"),
                MoleculeIndex(8, 1, "na"),
                MoleculeIndex(9, 1, "cl"),
            ],
            na_count=1,
            cl_count=1,
            report="test",
            # Solute attributes
            solute_type="CH4",
            solute_positions=np.zeros((5, 3)),
            solute_atom_names=["C", "H", "H", "H", "H"],
            solute_n_molecules=1,
            solute_molecule_indices=[(0, 5)],
            solute_registry=MoleculetypeRegistry(),
        )

        save_path, dialog_p, mb_p = mock_save_dialog("ions_with_solute.gro")
        exporter = IonGROMACSExporter(parent_widget=None)

        with dialog_p, mb_p:
            result = exporter.export_ion_gromacs(ion)

        assert result is True
        tmp_path = Path(save_path).parent
        # Solute liquid ITP should exist
        assert (tmp_path / "ch4_liquid.itp").exists()

    def test_custom_itp_copied_when_custom_present(self, mock_save_dialog):
        """Custom molecule ITP is copied when ion_structure has custom molecules.

        The exporter requires ALL THREE conditions:
        - custom_molecule_count > 0
        - custom_molecule_positions is not None
        - custom_itp_path exists as a file

        The copied custom ITP should have atomtypes commented out
        (via comment_out_atomtypes_in_itp).
        """
        custom_itp_path = Path("quickice/data/custom/etoh.itp")
        assert custom_itp_path.exists(), "etoh.itp must exist for this test"

        # Create IonStructure with custom molecules (ethanol)
        ion = IonStructure(
            positions=np.zeros((19, 3)),  # 8 water + 2 ions + 9 custom (ethanol)
            atom_names=[
                "OW", "HW1", "HW2", "MW",  # water mol 1
                "OW", "HW1", "HW2", "MW",  # water mol 2
                "NA",                       # sodium
                "CL",                       # chloride
                "H", "C", "H", "H", "C", "H", "H", "O", "H",  # ethanol
            ],
            cell=np.eye(3) * 3.0,
            molecule_index=[
                MoleculeIndex(0, 4, "water"),
                MoleculeIndex(4, 4, "water"),
                MoleculeIndex(8, 1, "na"),
                MoleculeIndex(9, 1, "cl"),
            ],
            na_count=1,
            cl_count=1,
            report="test",
            # Custom molecule attributes
            custom_molecule_count=1,
            custom_molecule_atom_count=9,
            custom_molecule_positions=np.zeros((9, 3)),
            custom_molecule_atom_names=["H", "C", "H", "H", "C", "H", "H", "O", "H"],
            custom_molecule_moleculetype="ETOH",
            custom_itp_path=custom_itp_path,
        )

        save_path, dialog_p, mb_p = mock_save_dialog("ions_with_custom.gro")
        exporter = IonGROMACSExporter(parent_widget=None)

        with dialog_p, mb_p:
            result = exporter.export_ion_gromacs(ion)

        assert result is True
        tmp_path = Path(save_path).parent
        # Custom ITP should exist
        assert (tmp_path / "etoh.itp").exists()

        # Verify atomtypes are commented out in the copied custom ITP
        custom_itp_content = (tmp_path / "etoh.itp").read_text()
        assert (
            "Modified for QuickIce" in custom_itp_content
            or "; [ atomtypes ]" in custom_itp_content
        ), "Custom ITP should have atomtypes commented out"
